sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t nsterdt94/docker -f Dockerfile.dev ./6_frontend

script:
  - docker run -e CI=true nsterdt94/docker npm run test